services:
  app:
    container_name: etamax-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      # Add other necessary variables here
    depends_on:
      - mongo
    networks:
      - etamax-network

  mongo:
    container_name: etamax-mongo
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - etamax-network

networks:
  etamax-network:
    driver: bridge

volumes:
  mongo-data:
